# Generated by Django 3.1.4 on 2020-12-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
