# Generated by Django 3.1.4 on 2020-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
